apiVersion: v1
kind: Service
metadata:
  name: maven-project-service
  labels:
    app: maven-project
spec:
  type: LoadBalancer
  selector:
    app: maven-project
  ports:
    - protocol: TCP
      port: 80          # Exposes service externally on port 80
      targetPort: 8080
